using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows;
using System.Windows.Interop;

namespace SmartPaste
{
    /// <summary>
    /// Intercepts the native Ctrl+V when SmartCopy content is available.
    ///
    /// Architecture:
    ///   1. Low-level keyboard hook (WH_KEYBOARD_LL) monitors all keystrokes
    ///   2. Clipboard format listener tracks whether SmartCopy content exists
    ///   3. When Ctrl+V is pressed AND SmartCopy content is tagged on clipboard:
    ///      → Suppress the keystroke
    ///      → Dispatch SmartInject on the UI thread
    ///      → SmartInject detects target app, sets optimal format, re-sends Ctrl+V
    ///   4. When no SmartCopy content → Ctrl+V passes through untouched
    ///   5. After injection, EndInject() re-reads the clipboard: the injected
    ///      content carries no tag, so the next plain Ctrl+V passes through
    ///
    /// The user never notices - Ctrl+V just works better.
    /// </summary>
    public class PasteInterceptor : IDisposable
    {
        // ── P/Invoke ─────────────────────────────────────────────────

        private delegate IntPtr LowLevelKeyboardProc(int nCode, IntPtr wParam, IntPtr lParam);

        [DllImport("user32.dll", SetLastError = true)]
        private static extern IntPtr SetWindowsHookEx(int idHook,
            LowLevelKeyboardProc lpfn, IntPtr hMod, uint dwThreadId);

        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool UnhookWindowsHookEx(IntPtr hhk);

        [DllImport("user32.dll")]
        private static extern IntPtr CallNextHookEx(IntPtr hhk,
            int nCode, IntPtr wParam, IntPtr lParam);

        [DllImport("kernel32.dll", CharSet = CharSet.Auto)]
        private static extern IntPtr GetModuleHandle(string? lpModuleName);

        [DllImport("user32.dll")]
        private static extern short GetAsyncKeyState(int vKey);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool AddClipboardFormatListener(IntPtr hwnd);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        private static extern bool RemoveClipboardFormatListener(IntPtr hwnd);

        // ── Constants ────────────────────────────────────────────────

        private const int WH_KEYBOARD_LL = 13;
        private const int WM_KEYDOWN = 0x0100;
        private const int WM_CLIPBOARDUPDATE = 0x031D;
        private const int VK_V = 0x56;
        private const int VK_CONTROL = 0x11;
        private const int VK_SHIFT = 0x10;
        private const int VK_MENU = 0x12;
        private const int VK_LWIN = 0x5B;
        private const int VK_RWIN = 0x5C;

        /// <summary>KBDLLHOOKSTRUCT.flags bit set for keystrokes generated by SendInput.</summary>
        private const int LLKHF_INJECTED = 0x10;
        private const int KbdLlHookStructFlagsOffset = 8;

        // ── State ────────────────────────────────────────────────────

        private readonly LowLevelKeyboardProc _hookProc;  // prevent GC
        private IntPtr _hookId;
        private readonly IntPtr _hwnd;
        private readonly Action _onSmartPaste;
        private HwndSource? _hwndSource;

        /// <summary>Fast in-memory flag - set by clipboard monitor, no disk I/O.</summary>
        private volatile bool _hasSmartContent;

        /// <summary>True while SmartInject is setting clipboard + sending Ctrl+V.</summary>
        private volatile bool _isInjecting;

        /// <summary>
        /// Start of the current injection. Physical Ctrl+V auto-repeats arriving inside
        /// this window are swallowed so a slightly long key press does not add a native
        /// paste on top of the smart one; the window is bounded so a stuck flag can
        /// never block Ctrl+V for good.
        /// </summary>
        private long _injectStartedAt;
        private const int RepeatSuppressWindowMs = 1000;

        /// <summary>Master switch - can be toggled via settings.</summary>
        public bool Enabled { get; set; } = true;

        // ── Construction ─────────────────────────────────────────────

        public PasteInterceptor(IntPtr hwnd, Action onSmartPaste)
        {
            _hwnd = hwnd;
            _onSmartPaste = onSmartPaste;

            // Install low-level keyboard hook
            _hookProc = HookCallback;
            using var process = Process.GetCurrentProcess();
            using var module = process.MainModule!;
            _hookId = SetWindowsHookEx(WH_KEYBOARD_LL, _hookProc,
                GetModuleHandle(module.ModuleName), 0);

            // Register for clipboard change notifications
            AddClipboardFormatListener(hwnd);
            _hwndSource = HwndSource.FromHwnd(hwnd);
            _hwndSource?.AddHook(WndProc);

            // Seed the flag from whatever is already on the clipboard
            RefreshSmartContentState();
        }

        // ── Injection control (called by App.xaml.cs) ────────────────

        /// <summary>
        /// Marks the start of an injection: clipboard updates are ignored and
        /// Ctrl+V is no longer intercepted until <see cref="EndInject"/>.
        /// </summary>
        public void BeginInject()
        {
            _injectStartedAt = Environment.TickCount64;
            _isInjecting = true;
        }

        /// <summary>
        /// Call after the injected Ctrl+V has been processed (UI/STA thread).
        /// Re-evaluates the clipboard before re-arming: the injected clipboard
        /// carries no CopyId tag, so a stale "smart content" flag would make the
        /// next plain Ctrl+V get intercepted and then aborted (nothing pasted).
        /// </summary>
        public void EndInject()
        {
            RefreshSmartContentState();
            _isInjecting = false;
        }

        /// <summary>
        /// Re-reads the clipboard and updates the in-memory "smart content" flag.
        /// Must be called from an STA thread (the WPF UI thread). If the clipboard
        /// stays locked the flag is cleared: a missed interception only costs a
        /// native paste, whereas a stale flag swallows the user's Ctrl+V.
        /// </summary>
        public void RefreshSmartContentState()
        {
            bool hasSmartContent = false;
            for (int attempt = 0; attempt < 3; attempt++)
            {
                try
                {
                    IDataObject? clip = Clipboard.GetDataObject();
                    hasSmartContent = clip?.GetDataPresent(FormatCache.CopyIdFormat) == true;
                    break;
                }
                catch (Exception)
                {
                    Thread.Sleep(25);   // clipboard busy - retry briefly
                }
            }
            _hasSmartContent = hasSmartContent;
        }

        // ── Keyboard hook ────────────────────────────────────────────

        private IntPtr HookCallback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            // Fast path: skip if disabled or when no SmartCopy content is tagged
            if (nCode >= 0
                && (int)wParam == WM_KEYDOWN
                && Enabled
                && _hasSmartContent)
            {
                int vkCode = Marshal.ReadInt32(lParam);
                int flags = Marshal.ReadInt32(lParam, KbdLlHookStructFlagsOffset);

                // Only act on a physical, pure Ctrl+V (not Ctrl+Shift+V, Ctrl+Alt+V, etc.).
                // Injected keystrokes are our own re-sent Ctrl+V - never intercept them.
                if (vkCode == VK_V && (flags & LLKHF_INJECTED) == 0 && IsPureCtrlV())
                {
                    if (_isInjecting)
                    {
                        // Auto-repeat of the Ctrl+V we are already handling → swallow it
                        // (bounded window: a stuck flag never blocks pasting for good)
                        bool insideWindow = Environment.TickCount64 - _injectStartedAt < RepeatSuppressWindowMs;
                        return insideWindow ? (IntPtr)1 : CallNextHookEx(_hookId, nCode, wParam, lParam);
                    }

                    var dispatcher = Application.Current?.Dispatcher;
                    if (dispatcher != null)
                    {
                        // Block re-entry until EndInject() re-arms us
                        BeginInject();

                        // Dispatch SmartInject on the UI thread
                        dispatcher.BeginInvoke(_onSmartPaste);

                        // Suppress the original Ctrl+V
                        return (IntPtr)1;
                    }
                }
            }

            return CallNextHookEx(_hookId, nCode, wParam, lParam);
        }

        /// <summary>
        /// Returns true only if Ctrl is held with NO other modifiers.
        /// This ensures we don't steal Ctrl+Shift+V, Ctrl+Alt+V, etc.
        /// </summary>
        private static bool IsPureCtrlV()
        {
            bool ctrl  = (GetAsyncKeyState(VK_CONTROL) & 0x8000) != 0;
            bool shift = (GetAsyncKeyState(VK_SHIFT)   & 0x8000) != 0;
            bool alt   = (GetAsyncKeyState(VK_MENU)    & 0x8000) != 0;
            bool win   = (GetAsyncKeyState(VK_LWIN)    & 0x8000) != 0
                      || (GetAsyncKeyState(VK_RWIN)    & 0x8000) != 0;

            return ctrl && !shift && !alt && !win;
        }

        // ── Clipboard monitoring ─────────────────────────────────────

        private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam,
            IntPtr lParam, ref bool handled)
        {
            if (msg == WM_CLIPBOARDUPDATE && !_isInjecting)
            {
                OnClipboardChanged();
            }
            return IntPtr.Zero;
        }

        /// <summary>
        /// Called on every clipboard change. Checks whether our CopyId tag
        /// is present - if so, SmartCopy content is available for injection.
        /// </summary>
        private void OnClipboardChanged()
        {
            try
            {
                IDataObject? clip = Clipboard.GetDataObject();
                _hasSmartContent = clip?.GetDataPresent(FormatCache.CopyIdFormat) == true;
            }
            catch
            {
                // Clipboard locked by another app - keep previous state
            }
        }

        // ── Disposal ─────────────────────────────────────────────────

        public void Dispose()
        {
            if (_hookId != IntPtr.Zero)
            {
                UnhookWindowsHookEx(_hookId);
                _hookId = IntPtr.Zero;
            }

            RemoveClipboardFormatListener(_hwnd);
            _hwndSource?.RemoveHook(WndProc);
        }
    }
}
