// <auto-generated> Strongly-typed accessor for Localization/Strings.resx (base English). </auto-generated>
using System.Globalization;
using System.Resources;

namespace SmartPaste.Localization
{
    /// <summary>
    /// All user-facing strings. Add a Strings.&lt;culture&gt;.resx next to Strings.resx to translate
    /// without touching code; lookups honour CultureInfo.CurrentUICulture.
    /// </summary>
    public static class Strings
    {
        private static readonly ResourceManager Manager =
            new ResourceManager("SmartPaste.Localization.Strings", typeof(Strings).Assembly);

        /// <summary>Returns the localized string for a key, or the key itself when missing.</summary>
        public static string Get(string key)
        {
            try { return Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key; }
            catch (MissingManifestResourceException) { return key; }
        }

        /// <summary>Formats a localized composite string.</summary>
        public static string Format(string key, params object[] args) =>
            string.Format(CultureInfo.CurrentCulture, Get(key), args);

        /// <summary>"Smart-Paste"</summary>
        public static string AppTitle => Get(nameof(AppTitle));
        /// <summary>"Smart-Paste - right-click for options"</summary>
        public static string TrayTooltip => Get(nameof(TrayTooltip));
        /// <summary>"Open"</summary>
        public static string TrayOpen => Get(nameof(TrayOpen));
        /// <summary>"Pause Ctrl+V interception"</summary>
        public static string TrayPauseIntercept => Get(nameof(TrayPauseIntercept));
        /// <summary>"Exit"</summary>
        public static string TrayExit => Get(nameof(TrayExit));
        /// <summary>"Settings"</summary>
        public static string SettingsButton => Get(nameof(SettingsButton));
        /// <summary>"Light / dark"</summary>
        public static string LightDarkToggle => Get(nameof(LightDarkToggle));
        /// <summary>"Telework"</summary>
        public static string TeleworkButton => Get(nameof(TeleworkButton));
        /// <summary>"By"</summary>
        public static string HubBy => Get(nameof(HubBy));
        /// <summary>"Hope 'n Mind"</summary>
        public static string HubCompany => Get(nameof(HubCompany));
        /// <summary>"Running · {0} active"</summary>
        public static string HubRunning => Get(nameof(HubRunning));
        /// <summary>"Hover a function to configure"</summary>
        public static string HubHint => Get(nameof(HubHint));
        /// <summary>"Enabled"</summary>
        public static string HubEnabled => Get(nameof(HubEnabled));
        /// <summary>"Smart Paste"</summary>
        public static string FeatureSmartPaste => Get(nameof(FeatureSmartPaste));
        /// <summary>"Type lists into any field."</summary>
        public static string FeatureSmartPasteDesc => Get(nameof(FeatureSmartPasteDesc));
        /// <summary>"Smart Copy"</summary>
        public static string FeatureSmartCopy => Get(nameof(FeatureSmartCopy));
        /// <summary>"Faithful web capture."</summary>
        public static string FeatureSmartCopyDesc => Get(nameof(FeatureSmartCopyDesc));
        /// <summary>"Always On Top"</summary>
        public static string FeatureAlwaysOnTop => Get(nameof(FeatureAlwaysOnTop));
        /// <summary>"Pin the active window."</summary>
        public static string FeatureAlwaysOnTopDesc => Get(nameof(FeatureAlwaysOnTopDesc));
        /// <summary>"Case Converter"</summary>
        public static string FeatureCaseConverter => Get(nameof(FeatureCaseConverter));
        /// <summary>"Cycle lower · UPPER · Title."</summary>
        public static string FeatureCaseConverterDesc => Get(nameof(FeatureCaseConverterDesc));
        /// <summary>"Aa"</summary>
        public static string CaseGlyph => Get(nameof(CaseGlyph));
        /// <summary>"Active"</summary>
        public static string StatusActive => Get(nameof(StatusActive));
        /// <summary>"Off"</summary>
        public static string StatusOff => Get(nameof(StatusOff));
        /// <summary>"Enter"</summary>
        public static string ModeEnter => Get(nameof(ModeEnter));
        /// <summary>"Space"</summary>
        public static string ModeSpace => Get(nameof(ModeSpace));
        /// <summary>"Normal"</summary>
        public static string ModeNormal => Get(nameof(ModeNormal));
        /// <summary>"Target-aware"</summary>
        public static string OptTargetAware => Get(nameof(OptTargetAware));
        /// <summary>"Embed SVG"</summary>
        public static string OptEmbedSvg => Get(nameof(OptEmbedSvg));
        /// <summary>"Settings"</summary>
        public static string SettingsTitle => Get(nameof(SettingsTitle));
        /// <summary>"✕"</summary>
        public static string CloseGlyph => Get(nameof(CloseGlyph));
        /// <summary>"Colour theme"</summary>
        public static string LabelColourTheme => Get(nameof(LabelColourTheme));
        /// <summary>"Aubergine &amp; Or"</summary>
        public static string ThemeAubergine => Get(nameof(ThemeAubergine));
        /// <summary>"Prune &amp; Chartreuse"</summary>
        public static string ThemePrune => Get(nameof(ThemePrune));
        /// <summary>"Startup"</summary>
        public static string LabelStartup => Get(nameof(LabelStartup));
        /// <summary>"Start with Windows"</summary>
        public static string StartWithWindows => Get(nameof(StartWithWindows));
        /// <summary>"Start minimized to tray"</summary>
        public static string StartMinimized => Get(nameof(StartMinimized));
        /// <summary>"Intercept Ctrl+V for Smart Copy"</summary>
        public static string InterceptCtrlV => Get(nameof(InterceptCtrlV));
        /// <summary>"Shortcuts - click to rebind"</summary>
        public static string LabelShortcuts => Get(nameof(LabelShortcuts));
        /// <summary>"Smart Paste - Enter"</summary>
        public static string ShortcutSmartPasteEnter => Get(nameof(ShortcutSmartPasteEnter));
        /// <summary>"Smart Paste - Space"</summary>
        public static string ShortcutSmartPasteSpace => Get(nameof(ShortcutSmartPasteSpace));
        /// <summary>"Smart Paste - Normal"</summary>
        public static string ShortcutSmartPasteNormal => Get(nameof(ShortcutSmartPasteNormal));
        /// <summary>"Case Converter"</summary>
        public static string ShortcutCaseConverter => Get(nameof(ShortcutCaseConverter));
        /// <summary>"Always On Top"</summary>
        public static string ShortcutAlwaysOnTop => Get(nameof(ShortcutAlwaysOnTop));
        /// <summary>"Smart Copy"</summary>
        public static string ShortcutSmartCopy => Get(nameof(ShortcutSmartCopy));
        /// <summary>"Telework"</summary>
        public static string ShortcutTelework => Get(nameof(ShortcutTelework));
        /// <summary>"Reset to defaults"</summary>
        public static string ResetDefaults => Get(nameof(ResetDefaults));
        /// <summary>"Telework - human typing"</summary>
        public static string TeleworkTitle => Get(nameof(TeleworkTitle));
        /// <summary>"For fields that block paste · accessibility · QA. Mixed to feel naturally human."</summary>
        public static string TeleworkIntro => Get(nameof(TeleworkIntro));
        /// <summary>"Core"</summary>
        public static string LabelCore => Get(nameof(LabelCore));
        /// <summary>"Variable rhythm"</summary>
        public static string TeleVariableRhythm => Get(nameof(TeleVariableRhythm));
        /// <summary>"Randomized delay between keystrokes"</summary>
        public static string TeleVariableRhythmSub => Get(nameof(TeleVariableRhythmSub));
        /// <summary>"Micro-pauses"</summary>
        public static string TeleMicroPauses => Get(nameof(TeleMicroPauses));
        /// <summary>"Occasional “thinking” pauses"</summary>
        public static string TeleMicroPausesSub => Get(nameof(TeleMicroPausesSub));
        /// <summary>"Flow bursts"</summary>
        public static string TeleFlowBursts => Get(nameof(TeleFlowBursts));
        /// <summary>"Short accelerations"</summary>
        public static string TeleFlowBurstsSub => Get(nameof(TeleFlowBurstsSub));
        /// <summary>"Breathing pauses"</summary>
        public static string TeleBreathing => Get(nameof(TeleBreathing));
        /// <summary>"Periodic longer rests"</summary>
        public static string TeleBreathingSub => Get(nameof(TeleBreathingSub));
        /// <summary>"End-of-line pause"</summary>
        public static string TeleEndOfLine => Get(nameof(TeleEndOfLine));
        /// <summary>"Pause after Enter / newline"</summary>
        public static string TeleEndOfLineSub => Get(nameof(TeleEndOfLineSub));
        /// <summary>"Realistic errors"</summary>
        public static string LabelErrors => Get(nameof(LabelErrors));
        /// <summary>"Typos"</summary>
        public static string TeleTypos => Get(nameof(TeleTypos));
        /// <summary>"Wrong key → backspace → retype"</summary>
        public static string TeleTyposSub => Get(nameof(TeleTyposSub));
        /// <summary>"Caps errors"</summary>
        public static string TeleCapsErrors => Get(nameof(TeleCapsErrors));
        /// <summary>"Double key-strokes"</summary>
        public static string TeleDoubleKeys => Get(nameof(TeleDoubleKeys));
        /// <summary>"Cursor navigation"</summary>
        public static string TeleCursorNav => Get(nameof(TeleCursorNav));
        /// <summary>"Arrow-key corrections"</summary>
        public static string TeleCursorNavSub => Get(nameof(TeleCursorNavSub));
        /// <summary>"Auto-correct mistakes"</summary>
        public static string TeleAutoCorrect => Get(nameof(TeleAutoCorrect));
        /// <summary>"Base speed · {0} ms"</summary>
        public static string LabelBaseSpeed => Get(nameof(LabelBaseSpeed));
        /// <summary>"Timing"</summary>
        public static string LabelTiming => Get(nameof(LabelTiming));
        /// <summary>"Telework delay · {0} ms"</summary>
        public static string TeleDelay => Get(nameof(TeleDelay));
        /// <summary>"Word chunk · {0} chars"</summary>
        public static string TeleChunk => Get(nameof(TeleChunk));
        /// <summary>"Breathing every · {0} chars"</summary>
        public static string TeleBreathInterval => Get(nameof(TeleBreathInterval));
        /// <summary>"Rebind - {0}"</summary>
        public static string ShortcutEditorTitle => Get(nameof(ShortcutEditorTitle));
        /// <summary>"Press the combination…"</summary>
        public static string CapturePrompt => Get(nameof(CapturePrompt));
        /// <summary>"{0} + …"</summary>
        public static string CaptureModifiersOnly => Get(nameof(CaptureModifiersOnly));
        /// <summary>"Ctrl / Alt / Win + key, or a function key alone. Esc cancels."</summary>
        public static string CaptureHint => Get(nameof(CaptureHint));
        /// <summary>"Add Ctrl, Alt or Win - or use a function key alone."</summary>
        public static string ErrorNeedModifier => Get(nameof(ErrorNeedModifier));
        /// <summary>"Shift alone conflicts with normal typing."</summary>
        public static string ErrorShiftOnly => Get(nameof(ErrorShiftOnly));
        /// <summary>"Reserved by Windows: {0}"</summary>
        public static string ErrorReserved => Get(nameof(ErrorReserved));
        /// <summary>"This key is not supported."</summary>
        public static string ErrorUnsupported => Get(nameof(ErrorUnsupported));
        /// <summary>"Already used by {0}."</summary>
        public static string ErrorDuplicate => Get(nameof(ErrorDuplicate));
        /// <summary>"Apply"</summary>
        public static string Apply => Get(nameof(Apply));
        /// <summary>"Cancel"</summary>
        public static string Cancel => Get(nameof(Cancel));
        /// <summary>"lock the computer"</summary>
        public static string ReservedLock => Get(nameof(ReservedLock));
        /// <summary>"task switcher"</summary>
        public static string ReservedTaskSwitch => Get(nameof(ReservedTaskSwitch));
        /// <summary>"close window"</summary>
        public static string ReservedCloseWindow => Get(nameof(ReservedCloseWindow));
        /// <summary>"show desktop"</summary>
        public static string ReservedShowDesktop => Get(nameof(ReservedShowDesktop));
        /// <summary>"File Explorer"</summary>
        public static string ReservedExplorer => Get(nameof(ReservedExplorer));
        /// <summary>"Run dialog"</summary>
        public static string ReservedRun => Get(nameof(ReservedRun));
        /// <summary>"Search"</summary>
        public static string ReservedSearch => Get(nameof(ReservedSearch));
        /// <summary>"Windows Settings"</summary>
        public static string ReservedSettings => Get(nameof(ReservedSettings));
        /// <summary>"Task View"</summary>
        public static string ReservedTaskView => Get(nameof(ReservedTaskView));
        /// <summary>"security screen"</summary>
        public static string ReservedSecurity => Get(nameof(ReservedSecurity));
        /// <summary>"Task Manager"</summary>
        public static string ReservedTaskManager => Get(nameof(ReservedTaskManager));
        /// <summary>"Start menu"</summary>
        public static string ReservedStart => Get(nameof(ReservedStart));
        /// <summary>"Quick Link menu"</summary>
        public static string ReservedQuickLink => Get(nameof(ReservedQuickLink));
        /// <summary>"notification center"</summary>
        public static string ReservedActionCenter => Get(nameof(ReservedActionCenter));
        /// <summary>"clipboard history"</summary>
        public static string ReservedClipboardHistory => Get(nameof(ReservedClipboardHistory));
        /// <summary>"screen snipping"</summary>
        public static string ReservedSnip => Get(nameof(ReservedSnip));
        /// <summary>"project display"</summary>
        public static string ReservedProject => Get(nameof(ReservedProject));
        /// <summary>"Game Bar"</summary>
        public static string ReservedGameBar => Get(nameof(ReservedGameBar));
        /// <summary>"voice typing"</summary>
        public static string ReservedVoiceTyping => Get(nameof(ReservedVoiceTyping));
        /// <summary>"accessibility settings"</summary>
        public static string ReservedAccessibility => Get(nameof(ReservedAccessibility));
        /// <summary>"emoji panel"</summary>
        public static string ReservedEmoji => Get(nameof(ReservedEmoji));
        /// <summary>"virtual desktops"</summary>
        public static string ReservedVirtualDesktop => Get(nameof(ReservedVirtualDesktop));
        /// <summary>"minimize all windows"</summary>
        public static string ReservedMinimizeAll => Get(nameof(ReservedMinimizeAll));
        /// <summary>"Connect panel"</summary>
        public static string ReservedConnect => Get(nameof(ReservedConnect));
        /// <summary>"Magnifier"</summary>
        public static string ReservedMagnifier => Get(nameof(ReservedMagnifier));
        /// <summary>"Narrator"</summary>
        public static string ReservedNarrator => Get(nameof(ReservedNarrator));

        /// <summary>"Dark mode"</summary>
        public static string TrayDarkMode => Get(nameof(TrayDarkMode));
        /// <summary>"Shortcuts"</summary>
        public static string TrayShortcuts => Get(nameof(TrayShortcuts));
        /// <summary>"Open full panel…"</summary>
        public static string TrayOpenPanel => Get(nameof(TrayOpenPanel));
        /// <summary>"Minimize to tray"</summary>
        public static string MinimizeToTray => Get(nameof(MinimizeToTray));
        /// <summary>"Copy once. Paste anywhere."</summary>
        public static string ClaimTitle => Get(nameof(ClaimTitle));
        /// <summary>"Images, equations &amp; formatting - kept intact."</summary>
        public static string ClaimSub => Get(nameof(ClaimSub));
        /// <summary>"Type from a file"</summary>
        public static string TeleFileTitle => Get(nameof(TeleFileTitle));
        /// <summary>"No file loaded"</summary>
        public static string TeleFileNone => Get(nameof(TeleFileNone));
        /// <summary>"Load file…"</summary>
        public static string TeleLoadFile => Get(nameof(TeleLoadFile));
        /// <summary>"Type it (3 s)"</summary>
        public static string TeleTypeNow => Get(nameof(TeleTypeNow));
        /// <summary>"{0} · {1} chars"</summary>
        public static string TeleFileLoaded => Get(nameof(TeleFileLoaded));
        /// <summary>"Telework typing"</summary>
        public static string TeleTypingTitle => Get(nameof(TeleTypingTitle));
        /// <summary>"Press Esc to stop"</summary>
        public static string TeleStopHint => Get(nameof(TeleStopHint));
        /// <summary>"Stop"</summary>
        public static string TeleStop => Get(nameof(TeleStop));
        /// <summary>"Starting… focus your target"</summary>
        public static string TeleStarting => Get(nameof(TeleStarting));
    }
}
